name: CUSTOMtronics
favicon: null
layout_spectrum: 0.6249734712764621
typography_spectrum: 0.3627393143251538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2287015737965703
  lightness: 0.537904183845967
  saturation: 0.450977818807587
  rhythmicContrast: 0.20038806879892945
purpose: []
